// opcodes.h - 6510 CPU opcode metadata table.
//
// `opcodeTable[op]` returns the mnemonic, addressing mode, instruction size
// (bytes), base cycle count, and an `illegal` flag for every 8-bit opcode.
// Cycle counts are the base count only - page-crossing penalties for some
// addressing modes and branch-taken penalties are added by the executor.
#pragma once

#include <cstdint>

enum AddressingMode {
    MODE_IMPLIED,
    MODE_IMMEDIATE,
    MODE_ZERO_PAGE,
    MODE_ZERO_PAGE_X,
    MODE_ZERO_PAGE_Y,
    MODE_ABSOLUTE,
    MODE_ABSOLUTE_X,
    MODE_ABSOLUTE_Y,
    MODE_INDIRECT,
    MODE_INDIRECT_X,
    MODE_INDIRECT_Y,
    MODE_RELATIVE,
    MODE_ACCUMULATOR
};

struct OpcodeInfo {
    const char* mnemonic;
    uint8_t mode;
    uint8_t size;
    uint8_t cycles;
    bool illegal;  // Undocumented/illegal NMOS 6502/6510 opcode.
};

// Indexed directly by opcode byte (0x00-0xFF). Mnemonics are lowercase to
// match the disassembler output. `kil` entries trap the CPU on real hardware.
static const OpcodeInfo opcodeTable[256] = {
    // 0x00-0x0F
    {"brk", MODE_IMPLIED, 1, 7, false},
    {"ora", MODE_INDIRECT_X, 2, 6, false},
    {"kil", MODE_IMPLIED, 1, 0, true},
    {"slo", MODE_INDIRECT_X, 2, 8, true},
    {"nop", MODE_ZERO_PAGE, 2, 3, true},
    {"ora", MODE_ZERO_PAGE, 2, 3, false},
    {"asl", MODE_ZERO_PAGE, 2, 5, false},
    {"slo", MODE_ZERO_PAGE, 2, 5, true},
    {"php", MODE_IMPLIED, 1, 3, false},
    {"ora", MODE_IMMEDIATE, 2, 2, false},
    {"asl", MODE_ACCUMULATOR, 1, 2, false},
    {"anc", MODE_IMMEDIATE, 2, 2, true},
    {"nop", MODE_ABSOLUTE, 3, 4, true},
    {"ora", MODE_ABSOLUTE, 3, 4, false},
    {"asl", MODE_ABSOLUTE, 3, 6, false},
    {"slo", MODE_ABSOLUTE, 3, 6, true},

    // 0x10-0x1F
    {"bpl", MODE_RELATIVE, 2, 2, false},
    {"ora", MODE_INDIRECT_Y, 2, 5, false},
    {"kil", MODE_IMPLIED, 1, 0, true},
    {"slo", MODE_INDIRECT_Y, 2, 8, true},
    {"nop", MODE_ZERO_PAGE_X, 2, 4, true},
    {"ora", MODE_ZERO_PAGE_X, 2, 4, false},
    {"asl", MODE_ZERO_PAGE_X, 2, 6, false},
    {"slo", MODE_ZERO_PAGE_X, 2, 6, true},
    {"clc", MODE_IMPLIED, 1, 2, false},
    {"ora", MODE_ABSOLUTE_Y, 3, 4, false},
    {"nop", MODE_IMPLIED, 1, 2, true},
    {"slo", MODE_ABSOLUTE_Y, 3, 7, true},
    {"nop", MODE_ABSOLUTE_X, 3, 4, true},
    {"ora", MODE_ABSOLUTE_X, 3, 4, false},
    {"asl", MODE_ABSOLUTE_X, 3, 7, false},
    {"slo", MODE_ABSOLUTE_X, 3, 7, true},

    // 0x20-0x2F
    {"jsr", MODE_ABSOLUTE, 3, 6, false},
    {"and", MODE_INDIRECT_X, 2, 6, false},
    {"kil", MODE_IMPLIED, 1, 0, true},
    {"rla", MODE_INDIRECT_X, 2, 8, true},
    {"bit", MODE_ZERO_PAGE, 2, 3, false},
    {"and", MODE_ZERO_PAGE, 2, 3, false},
    {"rol", MODE_ZERO_PAGE, 2, 5, false},
    {"rla", MODE_ZERO_PAGE, 2, 5, true},
    {"plp", MODE_IMPLIED, 1, 4, false},
    {"and", MODE_IMMEDIATE, 2, 2, false},
    {"rol", MODE_ACCUMULATOR, 1, 2, false},
    {"anc", MODE_IMMEDIATE, 2, 2, true},
    {"bit", MODE_ABSOLUTE, 3, 4, false},
    {"and", MODE_ABSOLUTE, 3, 4, false},
    {"rol", MODE_ABSOLUTE, 3, 6, false},
    {"rla", MODE_ABSOLUTE, 3, 6, true},

    // 0x30-0x3F
    {"bmi", MODE_RELATIVE, 2, 2, false},
    {"and", MODE_INDIRECT_Y, 2, 5, false},
    {"kil", MODE_IMPLIED, 1, 0, true},
    {"rla", MODE_INDIRECT_Y, 2, 8, true},
    {"nop", MODE_ZERO_PAGE_X, 2, 4, true},
    {"and", MODE_ZERO_PAGE_X, 2, 4, false},
    {"rol", MODE_ZERO_PAGE_X, 2, 6, false},
    {"rla", MODE_ZERO_PAGE_X, 2, 6, true},
    {"sec", MODE_IMPLIED, 1, 2, false},
    {"and", MODE_ABSOLUTE_Y, 3, 4, false},
    {"nop", MODE_IMPLIED, 1, 2, true},
    {"rla", MODE_ABSOLUTE_Y, 3, 7, true},
    {"nop", MODE_ABSOLUTE_X, 3, 4, true},
    {"and", MODE_ABSOLUTE_X, 3, 4, false},
    {"rol", MODE_ABSOLUTE_X, 3, 7, false},
    {"rla", MODE_ABSOLUTE_X, 3, 7, true},

    // 0x40-0x4F
    {"rti", MODE_IMPLIED, 1, 6, false},
    {"eor", MODE_INDIRECT_X, 2, 6, false},
    {"kil", MODE_IMPLIED, 1, 0, true},
    {"sre", MODE_INDIRECT_X, 2, 8, true},
    {"nop", MODE_ZERO_PAGE, 2, 3, true},
    {"eor", MODE_ZERO_PAGE, 2, 3, false},
    {"lsr", MODE_ZERO_PAGE, 2, 5, false},
    {"sre", MODE_ZERO_PAGE, 2, 5, true},
    {"pha", MODE_IMPLIED, 1, 3, false},
    {"eor", MODE_IMMEDIATE, 2, 2, false},
    {"lsr", MODE_ACCUMULATOR, 1, 2, false},
    {"alr", MODE_IMMEDIATE, 2, 2, true},
    {"jmp", MODE_ABSOLUTE, 3, 3, false},
    {"eor", MODE_ABSOLUTE, 3, 4, false},
    {"lsr", MODE_ABSOLUTE, 3, 6, false},
    {"sre", MODE_ABSOLUTE, 3, 6, true},

    // 0x50-0x5F
    {"bvc", MODE_RELATIVE, 2, 2, false},
    {"eor", MODE_INDIRECT_Y, 2, 5, false},
    {"kil", MODE_IMPLIED, 1, 0, true},
    {"sre", MODE_INDIRECT_Y, 2, 8, true},
    {"nop", MODE_ZERO_PAGE_X, 2, 4, true},
    {"eor", MODE_ZERO_PAGE_X, 2, 4, false},
    {"lsr", MODE_ZERO_PAGE_X, 2, 6, false},
    {"sre", MODE_ZERO_PAGE_X, 2, 6, true},
    {"cli", MODE_IMPLIED, 1, 2, false},
    {"eor", MODE_ABSOLUTE_Y, 3, 4, false},
    {"nop", MODE_IMPLIED, 1, 2, true},
    {"sre", MODE_ABSOLUTE_Y, 3, 7, true},
    {"nop", MODE_ABSOLUTE_X, 3, 4, true},
    {"eor", MODE_ABSOLUTE_X, 3, 4, false},
    {"lsr", MODE_ABSOLUTE_X, 3, 7, false},
    {"sre", MODE_ABSOLUTE_X, 3, 7, true},

    // 0x60-0x6F
    {"rts", MODE_IMPLIED, 1, 6, false},
    {"adc", MODE_INDIRECT_X, 2, 6, false},
    {"kil", MODE_IMPLIED, 1, 0, true},
    {"rra", MODE_INDIRECT_X, 2, 8, true},
    {"nop", MODE_ZERO_PAGE, 2, 3, true},
    {"adc", MODE_ZERO_PAGE, 2, 3, false},
    {"ror", MODE_ZERO_PAGE, 2, 5, false},
    {"rra", MODE_ZERO_PAGE, 2, 5, true},
    {"pla", MODE_IMPLIED, 1, 4, false},
    {"adc", MODE_IMMEDIATE, 2, 2, false},
    {"ror", MODE_ACCUMULATOR, 1, 2, false},
    {"arr", MODE_IMMEDIATE, 2, 2, true},
    {"jmp", MODE_INDIRECT, 3, 5, false},  // 6502 indirect-JMP page-boundary bug applies.
    {"adc", MODE_ABSOLUTE, 3, 4, false},
    {"ror", MODE_ABSOLUTE, 3, 6, false},
    {"rra", MODE_ABSOLUTE, 3, 6, true},

    // 0x70-0x7F
    {"bvs", MODE_RELATIVE, 2, 2, false},
    {"adc", MODE_INDIRECT_Y, 2, 5, false},
    {"kil", MODE_IMPLIED, 1, 0, true},
    {"rra", MODE_INDIRECT_Y, 2, 8, true},
    {"nop", MODE_ZERO_PAGE_X, 2, 4, true},
    {"adc", MODE_ZERO_PAGE_X, 2, 4, false},
    {"ror", MODE_ZERO_PAGE_X, 2, 6, false},
    {"rra", MODE_ZERO_PAGE_X, 2, 6, true},
    {"sei", MODE_IMPLIED, 1, 2, false},
    {"adc", MODE_ABSOLUTE_Y, 3, 4, false},
    {"nop", MODE_IMPLIED, 1, 2, true},
    {"rra", MODE_ABSOLUTE_Y, 3, 7, true},
    {"nop", MODE_ABSOLUTE_X, 3, 4, true},
    {"adc", MODE_ABSOLUTE_X, 3, 4, false},
    {"ror", MODE_ABSOLUTE_X, 3, 7, false},
    {"rra", MODE_ABSOLUTE_X, 3, 7, true},

    // 0x80-0x8F
    {"nop", MODE_IMMEDIATE, 2, 2, true},
    {"sta", MODE_INDIRECT_X, 2, 6, false},
    {"nop", MODE_IMMEDIATE, 2, 2, true},
    {"sax", MODE_INDIRECT_X, 2, 6, true},
    {"sty", MODE_ZERO_PAGE, 2, 3, false},
    {"sta", MODE_ZERO_PAGE, 2, 3, false},
    {"stx", MODE_ZERO_PAGE, 2, 3, false},
    {"sax", MODE_ZERO_PAGE, 2, 3, true},
    {"dey", MODE_IMPLIED, 1, 2, false},
    {"nop", MODE_IMMEDIATE, 2, 2, true},
    {"txa", MODE_IMPLIED, 1, 2, false},
    {"xaa", MODE_IMMEDIATE, 2, 2, true},  // Highly unstable on real hardware.
    {"sty", MODE_ABSOLUTE, 3, 4, false},
    {"sta", MODE_ABSOLUTE, 3, 4, false},
    {"stx", MODE_ABSOLUTE, 3, 4, false},
    {"sax", MODE_ABSOLUTE, 3, 4, true},

    // 0x90-0x9F
    {"bcc", MODE_RELATIVE, 2, 2, false},
    {"sta", MODE_INDIRECT_Y, 2, 6, false},
    {"kil", MODE_IMPLIED, 1, 0, true},
    {"ahx", MODE_INDIRECT_Y, 2, 6, true},
    {"sty", MODE_ZERO_PAGE_X, 2, 4, false},
    {"sta", MODE_ZERO_PAGE_X, 2, 4, false},
    {"stx", MODE_ZERO_PAGE_Y, 2, 4, false},
    {"sax", MODE_ZERO_PAGE_Y, 2, 4, true},
    {"tya", MODE_IMPLIED, 1, 2, false},
    {"sta", MODE_ABSOLUTE_Y, 3, 5, false},
    {"txs", MODE_IMPLIED, 1, 2, false},
    {"tas", MODE_ABSOLUTE_Y, 3, 5, true},
    {"shy", MODE_ABSOLUTE_X, 3, 5, true},
    {"sta", MODE_ABSOLUTE_X, 3, 5, false},
    {"shx", MODE_ABSOLUTE_Y, 3, 5, true},
    {"ahx", MODE_ABSOLUTE_Y, 3, 5, true},

    // 0xA0-0xAF
    {"ldy", MODE_IMMEDIATE, 2, 2, false},
    {"lda", MODE_INDIRECT_X, 2, 6, false},
    {"ldx", MODE_IMMEDIATE, 2, 2, false},
    {"lax", MODE_INDIRECT_X, 2, 6, true},
    {"ldy", MODE_ZERO_PAGE, 2, 3, false},
    {"lda", MODE_ZERO_PAGE, 2, 3, false},
    {"ldx", MODE_ZERO_PAGE, 2, 3, false},
    {"lax", MODE_ZERO_PAGE, 2, 3, true},
    {"tay", MODE_IMPLIED, 1, 2, false},
    {"lda", MODE_IMMEDIATE, 2, 2, false},
    {"tax", MODE_IMPLIED, 1, 2, false},
    {"lax", MODE_IMMEDIATE, 2, 2, true},
    {"ldy", MODE_ABSOLUTE, 3, 4, false},
    {"lda", MODE_ABSOLUTE, 3, 4, false},
    {"ldx", MODE_ABSOLUTE, 3, 4, false},
    {"lax", MODE_ABSOLUTE, 3, 4, true},

    // 0xB0-0xBF
    {"bcs", MODE_RELATIVE, 2, 2, false},
    {"lda", MODE_INDIRECT_Y, 2, 5, false},
    {"kil", MODE_IMPLIED, 1, 0, true},
    {"lax", MODE_INDIRECT_Y, 2, 5, true},
    {"ldy", MODE_ZERO_PAGE_X, 2, 4, false},
    {"lda", MODE_ZERO_PAGE_X, 2, 4, false},
    {"ldx", MODE_ZERO_PAGE_Y, 2, 4, false},
    {"lax", MODE_ZERO_PAGE_Y, 2, 4, true},
    {"clv", MODE_IMPLIED, 1, 2, false},
    {"lda", MODE_ABSOLUTE_Y, 3, 4, false},
    {"tsx", MODE_IMPLIED, 1, 2, false},
    {"las", MODE_ABSOLUTE_Y, 3, 4, true},
    {"ldy", MODE_ABSOLUTE_X, 3, 4, false},
    {"lda", MODE_ABSOLUTE_X, 3, 4, false},
    {"ldx", MODE_ABSOLUTE_Y, 3, 4, false},
    {"lax", MODE_ABSOLUTE_Y, 3, 4, true},

    // 0xC0-0xCF
    {"cpy", MODE_IMMEDIATE, 2, 2, false},
    {"cmp", MODE_INDIRECT_X, 2, 6, false},
    {"nop", MODE_IMMEDIATE, 2, 2, true},
    {"dcp", MODE_INDIRECT_X, 2, 8, true},
    {"cpy", MODE_ZERO_PAGE, 2, 3, false},
    {"cmp", MODE_ZERO_PAGE, 2, 3, false},
    {"dec", MODE_ZERO_PAGE, 2, 5, false},
    {"dcp", MODE_ZERO_PAGE, 2, 5, true},
    {"iny", MODE_IMPLIED, 1, 2, false},
    {"cmp", MODE_IMMEDIATE, 2, 2, false},
    {"dex", MODE_IMPLIED, 1, 2, false},
    {"axs", MODE_IMMEDIATE, 2, 2, true},
    {"cpy", MODE_ABSOLUTE, 3, 4, false},
    {"cmp", MODE_ABSOLUTE, 3, 4, false},
    {"dec", MODE_ABSOLUTE, 3, 6, false},
    {"dcp", MODE_ABSOLUTE, 3, 6, true},

    // 0xD0-0xDF
    {"bne", MODE_RELATIVE, 2, 2, false},
    {"cmp", MODE_INDIRECT_Y, 2, 5, false},
    {"kil", MODE_IMPLIED, 1, 0, true},
    {"dcp", MODE_INDIRECT_Y, 2, 8, true},
    {"nop", MODE_ZERO_PAGE_X, 2, 4, true},
    {"cmp", MODE_ZERO_PAGE_X, 2, 4, false},
    {"dec", MODE_ZERO_PAGE_X, 2, 6, false},
    {"dcp", MODE_ZERO_PAGE_X, 2, 6, true},
    {"cld", MODE_IMPLIED, 1, 2, false},
    {"cmp", MODE_ABSOLUTE_Y, 3, 4, false},
    {"nop", MODE_IMPLIED, 1, 2, true},
    {"dcp", MODE_ABSOLUTE_Y, 3, 7, true},
    {"nop", MODE_ABSOLUTE_X, 3, 4, true},
    {"cmp", MODE_ABSOLUTE_X, 3, 4, false},
    {"dec", MODE_ABSOLUTE_X, 3, 7, false},
    {"dcp", MODE_ABSOLUTE_X, 3, 7, true},

    // 0xE0-0xEF
    {"cpx", MODE_IMMEDIATE, 2, 2, false},
    {"sbc", MODE_INDIRECT_X, 2, 6, false},
    {"nop", MODE_IMMEDIATE, 2, 2, true},
    {"isc", MODE_INDIRECT_X, 2, 8, true},
    {"cpx", MODE_ZERO_PAGE, 2, 3, false},
    {"sbc", MODE_ZERO_PAGE, 2, 3, false},
    {"inc", MODE_ZERO_PAGE, 2, 5, false},
    {"isc", MODE_ZERO_PAGE, 2, 5, true},
    {"inx", MODE_IMPLIED, 1, 2, false},
    {"sbc", MODE_IMMEDIATE, 2, 2, false},
    {"nop", MODE_IMPLIED, 1, 2, false},
    {"sbc", MODE_IMMEDIATE, 2, 2, true},  // Illegal alias of $E9.
    {"cpx", MODE_ABSOLUTE, 3, 4, false},
    {"sbc", MODE_ABSOLUTE, 3, 4, false},
    {"inc", MODE_ABSOLUTE, 3, 6, false},
    {"isc", MODE_ABSOLUTE, 3, 6, true},

    // 0xF0-0xFF
    {"beq", MODE_RELATIVE, 2, 2, false},
    {"sbc", MODE_INDIRECT_Y, 2, 5, false},
    {"kil", MODE_IMPLIED, 1, 0, true},
    {"isc", MODE_INDIRECT_Y, 2, 8, true},
    {"nop", MODE_ZERO_PAGE_X, 2, 4, true},
    {"sbc", MODE_ZERO_PAGE_X, 2, 4, false},
    {"inc", MODE_ZERO_PAGE_X, 2, 6, false},
    {"isc", MODE_ZERO_PAGE_X, 2, 6, true},
    {"sed", MODE_IMPLIED, 1, 2, false},
    {"sbc", MODE_ABSOLUTE_Y, 3, 4, false},
    {"nop", MODE_IMPLIED, 1, 2, true},
    {"isc", MODE_ABSOLUTE_Y, 3, 7, true},
    {"nop", MODE_ABSOLUTE_X, 3, 4, true},
    {"sbc", MODE_ABSOLUTE_X, 3, 4, false},
    {"inc", MODE_ABSOLUTE_X, 3, 7, false},
    {"isc", MODE_ABSOLUTE_X, 3, 7, true}
};

